USE [GD1C2014]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER TL_Rol_After_Update ON [LA_BANDA_DEL_CHAVO].[TL_Rol]
FOR UPDATE
AS
	DECLARE @Activo int;
	DECLARE @ID_Rol int;
	SET @Activo = (SELECT DISTINCT Activo FROM INSERTED);
	SET @ID_Rol = (SELECT DISTINCT ID_Rol FROM INSERTED);
	
	IF (@Activo = 0)
	BEGIN
		DELETE FROM [LA_BANDA_DEL_CHAVO].[TL_Usuario_Rol]
		WHERE ([ID_Rol] = @ID_Rol)
	END
GO